Translation To Character Generation User Interface*
DazedMTL/MySecretSummerVacation2 pull request #8
Opened 2023-08-25 10:51 UTC by JanForShort

*only tested in Vendo Machine In Tunnel dunno if will work in PENSION HOUSE RECOLLECTION IN 3RD FLOOR and SECRET DIARY MODE please test it before merging @dazedanon to make sure it doesn't broke a game tnx....

FROM HERE
![char editor trans](https://github.com/DazedMTL/MySecretSummerVacation2/assets/72688821/ce9c811a-030e-4e07-b4a1-392bdc45679a)
TO HERE
![beta](https://github.com/DazedMTL/MySecretSummerVacation2/assets/72688821/59b1272d-641f-48ee-9b02-e4d63eae463d)

2023-08-25 10:55 UTC, JanForShort commented
now
![image](https://github.com/DazedMTL/MySecretSummerVacation2/assets/72688821/d82ea012-27ff-40ef-aa3b-9235f93f5922)
i proofed it...i think .json language doesn't support space so i use a underscore "_"...

2023-08-26 17:56 UTC, JanForShort commented
UPDATE AS OF NOW: I TESTED IT NO BUGS OR ERROR on SLIDER

LOCATION: TESTED ON VENDO, RECOLLECTION ROOM IN 3RD FLOOR AND CRYSTAL CHARACTER MAKER IN SECRET DIARY MODE

2023-08-26 18:44 UTC, dazedanon requested changes
Just need to check the D_TEXT and make sure you aren't using normal spaces.

2023-08-26 18:44 UTC, dazedanon commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Stop Editing At 18"
Are these normal spaces or unicode space? If its the former you need to put _ for the spaces instead.

2023-08-26 18:44 UTC, dazedanon commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
Same here, D_TEXT can't have spaces.

2023-08-26 18:44 UTC, dazedanon commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
Same here

2023-08-26 18:44 UTC, dazedanon commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
Same here

2023-08-26 18:44 UTC, dazedanon commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
Same Here

2023-08-26 18:44 UTC, dazedanon commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
Same Here

2023-08-26 19:15 UTC, JanForShort commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
yep D_TEXT cannot have a space 
only in selection bar i think as you see in screenshot....

2023-08-26 19:15 UTC, JanForShort commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
okay...JUST DO what's the BEST FOR THAT SCRIPT DAZ...

2023-08-26 19:16 UTC, JanForShort commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
approved...

2023-08-26 19:16 UTC, JanForShort commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
Approved..

2023-08-26 19:16 UTC, JanForShort commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Return To The Adjustment Area Selection With 18"
Approved..

2023-08-26 19:17 UTC, JanForShort commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Stop Editing At 18"
D_TEXT COMMENTS doesn't have underscore...
only in SLIDER area i put because javascript i think doesn't support space...

2023-08-26 19:20 UTC, JanForShort commented
i leave everything to you daz. i know you what's best on that script...i already provided some necessary information needed,.

PS: currently playing with that script...hihihi

2023-08-26 19:24 UTC, JanForShort commented on www/data/Map024.json
> +                                "D_TEXT \"Cancel\"Stop Editing At 18"
> Are these normal spaces or unicode space? If its the former you need to put _ for the spaces instead.

ITS NORMAL SPACE AS YOU SEE IN SCREENSHOT I PROVIDED.

2023-08-26 20:21 UTC, dazedanon approved these changes

2023-08-26 20:21 UTC, merged